import { StyleSheet } from 'react-native';
import { colors } from '../../constants/Palette';

const styles = StyleSheet.create({
    mainViewFeedbacks:{
        width:'100%',
        backgroundColor:'#F2F4F4',
    },
    intro:{
        marginTop:'5%',
      },
    feedbacksText:{
        marginLeft:'5%',
        marginRight:'5%',
        marginBottom:'5%',
        marginTop:10,
        alignSelf:'center',
    },
    mainFormFeedbacks:{
      display:'flex',
      flexDirection:'column',
      alignItems:'flex-start',
      borderStyle:'solid',
      borderWidth:2,
      borderLeftColor:'#F08080',
      borderRightColor:"#fff",
      borderBottomColor:'#fff',
      borderTopColor:'#fff',
      borderLeftWidth:5,
      backgroundColor:'#fff',
      marginLeft:10,
      marginBottom:20,
      marginRight:10,
      width:'90%',
      alignSelf:'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
  },
  formFeedbacks:{
      width:'90%',
      display:'flex',
      flexDirection:'column',
      alignItems:'flex-start',
      alignSelf:'center',
      marginBottom:10,
      marginTop:5,
  },
  inputLabel1:{
      color:'black',
      fontWeight:'600',
      paddingLeft:10,
      paddingRight:10,
      marginBottom:5
  },
  button1: {
      backgroundColor: colors.primary_3,
      borderRadius: 10,
      padding: 10,
      alignItems: 'center',
      alignSelf:'center',
      width: 135,
      marginBottom: 10,
      marginTop:10,
      marginLeft:20,
    },
  buttonText: {
      color: colors.white,
      fontSize: 18,
    },
  input1: {
      borderColor:'#ccc',
      borderWidth:0.2,
      alignSelf:'center',
      backgroundColor: colors.white,
      borderRadius: 5,
      padding: 10,
      fontSize: 16,
      width:270,
    },
      generatedActivities:{
        margintop:'90%',
        marginleft:'5%',
        width:'90%',
        alignSelf:'center',
        display:'flex',
        flexDirection:'column',
        marginBottom:'5%',
      },
      activityView:{
        width:'100%',
        marginRight:'5%',
        marginLeft:'5%',
        borderStyle:'solid',
        backgroundColor:'white',
        borderWidth:2,
        borderLeftColor:"#fff",
        borderBottomColor:'#fff',
        borderTopColor:'#fff',
        borderRightWidth:5,
        borderRightColor:'#F08080',
        marginTop:20,
        alignSelf:'center',
        display:'flex',
        flexDirection:'column',
        shadowColor: '#000',
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        paddingLeft:10,
        paddingBottom:10,
        paddingRight:10,
        paddingTop:10,
        borderRadius:10,

        
    },
    activityName:{
      marginBottom:20, 
      textAlign:'center',
      color:colors.primary_1,
      fontWeight:'700',
    },
    activityDescription:{
      textAlign:'justify',
    },
});

export default styles;